### ISSUE TITLE
Focus issue. Having error in release mode...

### ISSUE THREAD

**Issue by ifasdev** [jelufe/input_with_keyboard_control#6]
Getting lost focus on the textfeild sometime while navigating the one screen to the another screen. 

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (29621): #0      View.of (package:flutter/src/widgets/view.dart:107)
E/flutter (29621): #1      EditableTextState.didChangeMetrics (package:flutter/src/widgets/editable_text.dart:3572)
E/flutter (29621): #2      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:586)
E/flutter (29621): #3      _invoke (dart:ui/hooks.dart:170)
E/flutter (29621): #4      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:329)
E/flutter (29621): #5      _updateWindowMetrics (dart:ui/hooks.dart:57)
E/flutter (29621): 
I/flutter (29621): Instance of 'MarkaNumberNotFound'
E/flutter (29621): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (29621): #0      View.of (package:flutter/src/widgets/view.dart:107)
E/flutter (29621): #1      EditableTextState.didChangeMetrics (package:flutter/src/widgets/editable_text.dart:3572)
E/flutter (29621): #2      WidgetsBinding.handleMetricsChanged (package:flutter/src/widgets/binding.dart:586)
E/flutter (29621): #3      _invoke (dart:ui/hooks.dart:170)
E/flutter (29621): #4      PlatformDispatcher._updateWindowMetrics (dart:ui/platform_dispatcher.dart:329)
E/flutter (29621): #5      _updateWindowMetrics (dart:ui/hooks.dart:57)
E/flutter (29621):

**Comment by mjmgooch** [comment]
@ifasdev this project seems inactive, but I've found it very useful for capturing input from a Bluetooth keyboard/controller and not having the keyboard show. I had the same issue as you, where the focus is lost when the app is resumed. I resolved this by adding the following code to the lib/input_with_keyboard_control.dart file and using my own version of this package.

Maybe if @jelufe sees this and approves, I will put this through as a pull request. 

```
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    super.didChangeAppLifecycleState(state);
    if (state == AppLifecycleState.resumed) {
      // Delaying the focus request to ensure the context is ready
      Future.delayed(Duration(milliseconds: 100), () {
        // Ensure the widget is still mounted before attempting to request focus
        if (mounted && !focusNode.hasFocus) {
          toggleShowKeyboard(false); 
        }
      });
    }
  }
```
